version: '3.8'

services:
  repo_builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cache:/app/cache
      - ./public:/app/public
      - ./scripts:/app/scripts
      - ./packages.txt:/app/packages.txt
      - ./website:/app/website  
    environment:
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - FORCE_REBUILD=${FORCE_REBUILD}
      - REPO_NAME=${REPO_NAME}
      - ARCH=${ARCH}
      - REPO_DIR=${REPO_DIR}
      - CACHE_DIR=${CACHE_DIR}
      - CHECKSUMS_FILE=${CHECKSUMS_FILE}
      - REMOTE_PACKAGES_FILE=${REMOTE_PACKAGES_FILE}
      - REBUILD_TRIGGER_FILE=${REBUILD_TRIGGER_FILE}
      - PACKAGES_CONFIG=${PACKAGES_CONFIG}
    command: /app/scripts/run.sh
    security_opt:
      - label=disable
    init: true
